<?php

use App\Http\Resources\QuoteResource;
use App\Jobs\GenerateQuote;
use App\Models\Quote;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return Inertia::render('Welcome');
})->name('home');

Route::post('/quotes', function (Request $request) {
    /** @var \App\Models\User $user */
    $user = $request->user();

    GenerateQuote::dispatch($user)->delay(30);

    return back()->with('success', 'A new quote will be generated by a background job. Refresh after 30 seconds to see it.');
})->name('quotes.store');

Route::get('dashboard', function (Request $request) {
    /** @var \App\Models\User $user */
    $user = $request->user();
    $records = Quote::whereNull('user_id')
        ->orWhereBelongsTo($user)
        ->orderByDesc('id')
        ->limit(10)
        ->get();

    return Inertia::render('Dashboard', [
        'success' => $request->session()->get('success'),
        'quotes' => QuoteResource::collection($records),
    ]);
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__.'/settings.php';
require __DIR__.'/auth.php';
