name: Ship

on:
  push:
    branches: ['main']

concurrency: staging_environment

jobs:
  staging:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://laravel.hapideploy.com

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: hapideploy/action@v1
        with:
          host: ${{ secrets.HAPI_HOST_IP }}
          user: ${{ secrets.HAPI_SSH_USER }}
          identity-key: ${{ secrets.HAPI_SSH_KEY }}
      - name: Run the deploy command
        run: |
          hapi deploy --stage=staging \
            --config=node_version=${{ vars.NODE_VERSION }},php_version=${{ vars.PHP_VERSION }}
